version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flaskapp
    container_name: api
    environment:
      - PORT=${PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
    volumes:
    - "./:/app"
      # - "./app:/app"
      # - /.venv
    ports:
      - 5000:${PORT}
    # depends_on:
    #   - db
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - pgflaskapp
    # command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
    # command: [ "./wait-for", "db:5432", "--", "bash", "entrypoint.sh" ]
    command: [ "bash", "entrypoint.sh" ]

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      pgflaskapp:
        aliases:
          - "postgres"

volumes:
  postgres-db:


networks:
  pgflaskapp:
    driver: bridge
